services:
  mysql-db:
    image: mysql:8.0.38
    restart: always
    environment:
      MYSQL_DATABASE: 'order'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: