server:
  port: 8080

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus,liveness,readiness,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true

logging:
  config: classpath:logback.xml

spring:
  profiles:
    active: local
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: true
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: test
  cloud:
    openfeign:
      client:
        config:
          mercadoPago:
            url: https://api.mercadopago.com

system:
  id-service: order-api
  sns:
    order: order.fifo
    order-client-notification: order-client-notification.fifo
    order-kitchen-notification: order-kitchen-notification.fifo

mercadoPago:
  userId: 39527093
  testToken: TEST-2711072900051385-071120-43d1b88b15c40770b83c59cb08d8628f-39527093
  externalPosId: SUC001